export default Permissions={
    Role:{
        ViewAll:"Permission.Role.ViewAll",
        ViewById:"Permission.Role.ViewById",
        Delete:"Permission.Role.Delete",
        Create:"Permission.Role.Create",
        ViewAllClaims:"Permission.Role.ViewAllClaims",
        UpdateRoleClaims:"Permission.Role.UpdateRoleClaims"
    },
    Student:{
        ViewAll:"Permission.Student.ViewAll",
        ViewById:"Permission.Student.ViewById",
        Delete:"Permission.Student.Delete",
        Create:"Permission.Student.Create",
        Update:"Permission.Student.Update"
    },
    Guardian:{
        ViewAll:"Permission.Guardian.ViewAll",
        ViewById:"Permission.Guardian.ViewById",
        Delete:"Permission.Guardian.Delete",
        Create:"Permission.Guardian.Create",
        Update:"Permission.Guardian.Update"
    },
    Instructor:{
        ViewAll:"Permission.Instructor.ViewAll",
        ViewById:"Permission.Instructor.ViewById",
        Delete:"Permission.Instructor.Delete",
        Create:"Permission.Instructor.Create",
        Update:"Permission.Instructor.Update"
    },
    Admin:{
        ViewAll:"Permission.Admin.ViewAll",
        ViewById:"Permission.Admin.ViewById",
        Delete:"Permission.Admin.Delete",
        Create:"Permission.Admin.Create",
        Update:"Permission.Admin.Update"
    },
    RelativeCard:{
        ViewAll:"Permission.RelativeCard.ViewAll",
        ViewById:"Permission.RelativeCard.ViewById",
        Delete:"Permission.RelativeCard.Delete",
        Create:"Permission.RelativeCard.Create",
        Update:"Permission.RelativeCard.Update"
    },
    StudentRelativeCard:{
        ViewAll:"Permission.StudentRelativeCard.ViewAll",
        ViewById:"Permission.StudentRelativeCard.ViewById",
        Delete:"Permission.StudentRelativeCard.Delete",
        Create:"Permission.StudentRelativeCard.Create",
        Update:"Permission.StudentRelativeCard.Update"
    },
    School:{
        ViewById:"Permission.School.ViewById",
        Update:"Permission.School.Update"
    },
    SchoolBranch:{
        ViewAll:"Permission.SchoolBranch.ViewAll",
        ViewById:"Permission.SchoolBranch.ViewById",
        Update:"Permission.SchoolBranch.Update",
        Create:"Permission.SchoolBranch.Create"
    },
    Department:{
        ViewAll:"Permission.Department.ViewAll",
        ViewById:"Permission.Department.ViewById",
        Delete:"Permission.Department.Delete",
        Create:"Permission.Department.Create",
        Update:"Permission.Department.Update"
    },
    Subject:{
        ViewAll:"Permission.Subject.ViewAll",
        ViewById:"Permission.Subject.ViewById",
        Delete:"Permission.Subject.Delete",
        Create:"Permission.Subject.Create",
        Update:"Permission.Subject.Update"
    },
    WorkingDay:{
        ViewAll:"Permission.WorkingDay.ViewAll",
        ViewById:"Permission.WorkingDay.ViewById",
        Delete:"Permission.WorkingDay.Delete",
        Create:"Permission.WorkingDay.Create",
        Update:"Permission.WorkingDay.Update"
    },
    AcademicYear:{
        ViewAll:"Permission.AcademicYear.ViewAll",
        ViewById:"Permission.AcademicYear.ViewById",
        Delete:"Permission.AcademicYear.Delete",
        Create:"Permission.AcademicYear.Create",
        Update:"Permission.AcademicYear.Update"
    },
    Grade:{
        ViewAll:"Permission.Grade.ViewAll",
        ViewById:"Permission.Grade.ViewById",
        Delete:"Permission.Grade.Delete",
        Create:"Permission.Grade.Create",
        Update:"Permission.Grade.Update"
    },
    Announcement:{
        ViewAll:"Permission.Announcement.ViewAll",
        ViewById:"Permission.Announcement.ViewById",
        Delete:"Permission.Announcement.Delete",
        Create:"Permission.Announcement.Create",
        Update:"Permission.Announcement.Update"
    },
    AnnouncementTarget:{
        ViewAll:"Permission.AnnouncementTarget.ViewAll",
        ViewById:"Permission.AnnouncementTarget.ViewById",
        Delete:"Permission.AnnouncementTarget.Delete",
        Create:"Permission.AnnouncementTarget.Create",
        Update:"Permission.AnnouncementTarget.Update"
    },
    Course:{
        ViewAll:"Permission.Course.ViewAll",
        ViewById:"Permission.Course.ViewById",
        Delete:"Permission.Course.Delete",
        Create:"Permission.Course.Create",
        Update:"Permission.Course.Update"
    },
    PlanDetail:{
        ViewAll:"Permission.PlanDetail.ViewAll",
        ViewById:"Permission.PlanDetail.ViewById",
        Delete:"Permission.PlanDetail.Delete",
        Create:"Permission.PlanDetail.Create",
        Update:"Permission.PlanDetail.Update"
    },
    InstructorCourse:{
        ViewAll:"Permission.InstructorCourse.ViewAll",
        ViewById:"Permission.InstructorCourse.ViewById",
        Delete:"Permission.InstructorCourse.Delete",
        Create:"Permission.InstructorCourse.Create",
        Update:"Permission.InstructorCourse.Update"
    }
}
 